# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    slugger:
        class: AppBundle\Utils\Slugger

    timedifference:
        class: AppBundle\Utils\TimeDifference

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%%kernel.default_locale%"]
        tags:
          - { name: kernel.event_subscriber }

    twig.timedifference:
        class: AppBundle\Twig\TimeDifference
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    twig.gravatar:
        class: AppBundle\Twig\Gravatar
        tags:
            - { name: twig.extension }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
